export const Names = {
  LeftPanel_TabButton: "tabButton",
  LeftPanel_SidePanel: "sidePanel",
  LeftPanel_SidePanelTitle: "sidePanelTitle",
  LeftPanel_SidePanelContent: "sidePanelContent",
  LeftPanel_SplitPaneDragger: "splitPaneDragger",
  RightPanel_SidebarButton1: "sidebarButton1",
  RightPanel_Sidebar1: "sidebar1",
  RightPanel_Dragger1: "dragger1",
  RightPanel_SidebarButton2: "sidebarButton2",
  RightPanel_Sidebar2: "sidebar2",
  RightPanel_Dragger2: "dragger2",
  RightPanel_SidebarButton3: "sidebarButton3",
  RightPanel_Sidebar3: "sidebar3",
  RightPanel_Dragger3: "dragger3",
  DataCategory: "data-category",
  DataCategory_Province: "data-category-province",
  DataCategory_Station: "data-category-station",
  DataCategory_Track: "data-category-track",
} as const;
